# IAM password security baseline

MIN_PASSWORD_LENGTH = 14
REQUIRE_UPPERCASE = True
REQUIRE_LOWERCASE = True
REQUIRE_NUMBERS = True
REQUIRE_SYMBOLS = True

MAX_PASSWORD_AGE_DAYS = 90
PASSWORD_REUSE_PREVENTION = 5
